language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install: "pip install -r requirements.txt"

script:
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy
  - nosetests -v
  - nosetests --with-doctest --doctest-extension doc/*.rst
